import { PrismaClient, Prisma } from '@prisma/client'

const prisma = new PrismaClient()

export const hotelData: Prisma.hotelCreateInput[] = [

{	
name:'HOTEL MENCEY',	
phoneNumber:'08(98)881-41-69',	
address:'CALLE DOCTOR JOSE NAVEIRAS 38',	
cityCountry:'BRASIL',	
email:'HOTEL MENCEY@correo.com',	
description:'Los servicios básicos incluyen el alojamiento y las comidas.',	
image:'',	
services:1,		
},
 {name:'HOTEL MENCEY',	phoneNumber:'08(98)881-41-69',	address:'CALLE DOCTOR JOSE NAVEIRAS 38',	cityCountry:'BRASIL',	email:'HOTEL MENCEY@correo.com',	description:'Los servicios básicos incluyen el alojamiento y las comidas. El registro de las personas dentro y fuera del hotel debe ser organizado las 24 horas del día. En las organizaciones de servicios de restauración, comunicación y consumo, se atiende prioritariamente a las personas alojadas en el hotel.',	image:'https://thumbs.dreamstime.com/b/orlando-florida-usa-august-funny-tow-cartoon-disney-moderate-hotels-funny-tow-cartoon-disney-moderate-hotels-131072600.jpg',	services:1,		},
 {	name:'HOTEL ADONIS CAPITAL',	phoneNumber:'1(6600)213-78-34',	address:'CALLE CRUZ VERDE 24',	cityCountry:'COLOMBIA',	email:'HOTEL ADONIS CAPITAL',	description:'Modern, elegant 4-star hotel overlooking the sea, perfect for a romantic, charming vacation, in the enchanting setting of Taormina and the Ionian Sea.',	image:'https://thumbs.dreamstime.com/b/hotel-rooms-8146308.jpg',	services:2,		},
{	name:'HOTEL PRINCIPE PAZ',	phoneNumber:'000(4077)592-75-20',	address:'CALLE VALENTIN SANZ 33',	cityCountry:'ARGENTINA',	email:'HOTEL PRINCIPE PAZname:',	description:'hotel boutique situado en el corazón del centro històrico de Florencia, rodeado de la extraordinaria belleza de iglesias, palacios y monumentos únicos en el mundo. El Duomo y la Galeria de la Accademia están a solo 5 minutos a pie.',	image:'https://thumbs.dreamstime.com/b/cancun-mexico-25252856.jpg',	services:3,		},
 {	name:'HOTEL TANAUSU',	phoneNumber:'163(66)802-63-66',	address:'CALLE PADRE ANCHIETA 8',	cityCountry:'MEXICO',	email:'HOTEL TANAUSUHOTEL MENCEY',	description:'Antigua mansión del siglo XIX, de propiedad de la familia Schuler fue convertida de una villa siciliana a un hotel en el año 1905. Es la empresa familiar hotelera más antigua de Taormina.',	image:' https://thumbs.dreamstime.com/b/street-signage-boa…background-editorial-d-united-states-85539251.jpg',	services:1,		},
 {	name:'HOTEL OCEANO',	phoneNumber:'76(16)945-87-34',	address:'CALLE CASTILLO 10',	cityCountry:'CHILE',	email:'HOTEL OCEANOHOTEL ADONIS CAPITAL',	description:'Disfrute de la ubicación céntrica y del elegante ambiente del Hotel Hilton Bogotá. Ubicado en el distrito financiero, el hotel se encuentra cerca de la Zona Rosa, una de las áreas más prestigiosas de la ciudad y de la Zona G, que ofrece entretenimiento y restaurantes. El Aeropuerto Internacional El Dorado está a 25 minutos. Relájese en el hotel Hilton Bogotá y disfrute de una ubicación ideal en el centro del distrito financiero de la ciudad. Disfrute de una habitación moderna con comodidades y servicios como WiFi y escritorio. ',	image:' https://thumbs.dreamstime.com/b/hilton-hotels-reso…tel-czech-republic-march-march-czech-69366095.jpg',	services:2,		},
 {	name:'HOTEL ATLANTICO',	phoneNumber:'3(10)360-75-09',	address:'CALLE CASTILLO 12',	cityCountry:'VENEZUELA',	email:'HOTEL ATLANTICOHOTEL PRINCIPE PAZ',	description:'With a privileged location, Hotel Continental Altamira is located in the financial center of the capital city and one of the safest areas of the country, where you can enjoy the greatest comfort in our renovated rooms, with personalized service, your stay a memorable experience Hotel Continental Altamira, Close to everything, Close to you!',	image:' https://thumbs.dreamstime.com/b/hotel-room-5802222.jpg',	services:3,		},
 {	name:'HOTELADONIS PLAZA',	phoneNumber:'39(3315)580-66-57',	address:'PLAZA DE CANDELARIA, 9',	cityCountry:'COLOMBIA',	email:'HOTELADONIS PLAZAHOTEL OCEANO',	description:'Galavilla Boutique Hotel  is located in the Central Province of Sri Lanka, 17.5 km (30 minutes) from the central old king‘s capital Kandy and overlooking the Knuckles mountain range, a part of the Hill Country. ',	image:' https://thumbs.dreamstime.com/b/south-beach-miami-hotels-18391986.jpg',	services:2,		},
 {	name:'HOTEL HORIZONTE',	phoneNumber:'72(50)913-02-95',	address:'CALLE SANTA ROSA DE LIMA 11',	cityCountry:'ARGENTINA',	email:'HOTEL HORIZONTEHOTEL ATLANTICO',	description:'Don Pepe, Hotel Boutique su Hotel en Santa Marta Colombia, ofrece a sus huéspedes experiencias de viaje que combinan descanso , historia y tradición en la ciudad más antigua de América. Cerca de una de las bahías más atractivas del Caribe, rodeada por la Sierra Nevada, el corazón del mundo según los ancestros, enmarcada en una construcción con siglos de historia, Don pepe se convierte en la opción mas representativa del Hotel de lujo en Santa Marta. 12 habitaciones, cuidadosamente detalladas, terrazas privadas, un Spa de terapias de lujo, el restaurante Bacota con una oferta gastronómica que combina sabores del mundo y la mejor atención de un personal calificado y comprometido lo esperan para atenderlo como usted merece.',	image:' https://thumbs.dreamstime.com/b/south-beach-hotels-night-14435805.jpg',	services:3,		},
 {	name:'HOTELAPARTAMENTO COLON RAMBLA',	phoneNumber:'488(214)505-56-10',	address:'CALLE VIERA Y CLAVIJO 49',	cityCountry:'MEXICO',	email:'HOTELAPARTAMENTO COLON RAMBLAHOTEL PELINOR',	description:'is located in the city centre, in Lisbon’s main business and shopping district. This renovated 5 stars combines the art and tradition of hospitality with all the facilities and services of an international unit. 303 Rooms and suites with panoramic terrace, completely soundproof, comfortably decorated and well equipped, guarantee a comfortable stay. The Hotel offers 2 Restaurants and 2 bars: Grill D. Fernando with panoramic view, and the Coffee Shop Rendez-Vous. A modern Business Centre, equipped with the latest technology, and wireless internet access in all meeting rooms and public areas. To make your stay even more enjoyable, the Altis offers a Health Club, heated Swimming pool, Shopping area, hairdresser, 24 Hours Room Service, Laundry and parking.',	image:' https://thumbs.dreamstime.com/b/south-beach-miami-hotels-18389048.jpg',	services:1,		},
 {	name:'HOTEL ESCUELA SANTA CRUZ',	phoneNumber:'567(765)905-38-52',	address:'AVENIDA SAN SEBASTIAN 152',	cityCountry:'CHILE',	email:'HOTEL ESCUELA SANTA CRUZHOTELADONIS PLAZA',	description:'Located on Avenida da Liberdade, right in the heart of Lisbon, this is an elegant 5 star hotel. Renowned for its business meeting facilities for top executives, Tivoli Lisboa continues the tradition of being a well known meeting point in the city. A weekend break in this luxury hotel means you can enjoy a drink in the privacy of the Terraço Bar with a superb view over Lisbon, or take a moment to relax in the Tivoli Caffè. We suggest a visit to our lively Brasserie Flo Lisbon restaurant which satisfies even the most discerning of palates. At the Terraço restaurant enjoy the selection of stylish dishes, accompanied by a unique view over the city of Lisbon.',	image:' https://thumbs.dreamstime.com/b/south-beach-hotels-night-14467563.jpg',	services:2,		},
 {	name:'HOTEL SILKEN ATLANTIDA',	phoneNumber:'152(42)918-45-15',	address:'CALLE AUREA DIAZ-FLORES HERNANDEZ, 2',	cityCountry:'VENEZUELA',	email:'HOTEL SILKEN ATLANTIDAHOTEL HORIZONTE',	description:'With its literary theme and excellent location in Lisbon`s historic centre, the newly-opened Eurostars Das Letras is a popular choice for visitors looking to experience the true essence of the Portuguese capital. Accommodation comprises 107 rooms (99 doubles, 6 suites and 2 for handicapped guests), all tastefully decorated with quality materials such as walnut wood and black and white marble. Facilities include 24-hour room service, Wi-Fi access, LCD TV in the rooms, restaurant, snack-bar, business area, fitness centre with sauna and private parking.',	image:' https://thumbs.dreamstime.com/b/cancun-coast-hotels-29500087.jpg',	services:3,		},
 {	name:'HOTEL NH TENERIFE',	phoneNumber:'72(20)738-88-27',	address:'CALLE CANDELARIA, 24',	cityCountry:'BRASIL',	email:'HOTEL NH TENERIFEHOTELAPARTAMENTO COLON RAMBLA',	description:'is located in one of the most privileged business areas of the city, just 15 minutes from Lisbon’s International airport and 10 minutes from the city’s downtown Baixa district. The Sheraton is now a brand-new hotel with a trendy look and feel and an extensive list of added features, most notably 369 totally renovated guest-rooms, including 10 junior suites and a sumptuous 155 square-meter presidential suite with private Jacuzzi. All the rooms are equipped with the exclusive Sheraton Sweet Sleeper bed, LCD Bang & Olufsen television, elegant glass bathroom, high-speed Wi-Fi Internet access, individually-controlled air-conditioning, mini-bar and with ironing board. Affording fantastic views over Lisbon, the new and very glamorous top-floor Panorama Restaurant and Panorama Bar is remarkable for its gourmet cuisine, show cooking and impressive glass wine storage area, setting a new standard in the concept of entertainment and high-quality urban gastronomy. The perfect setting can be found in the hotel lobby where a fresh design and high degree of functionality complement the bar and all-day-dining Lobby Bistro, the ideal place for an informal meeting or business lunch. The new-look Sheraton is fully complete with its ultra-modern Spa centre, covering a total area of 1,500 square meters. Facilities include 10 treatment rooms, a heated outdoor swimming pool, fitness room, Jacuzzi, sauna, chill-out areas and juice bar.',	image:' https://thumbs.dreamstime.com/b/dubrovnik-gulf-hotels-clear-water-38792570.jpg',	services:1,		},
 {	name:'HOTEL BARCELO CONTEMPORANEO',	phoneNumber:'45(086)014-29-87',	address:'RAMBLA DE SANTA CRUZ, 116',	cityCountry:'COLOMBIA',	email:'HOTEL BARCELO CONTEMPORANEOHOTEL ESCUELA SANTA CRUZ',	description:'Situated in the City Center on the fashionable Avenida da Liberdade the Sofitel Lisboa invites you to discover the typical old quarters of Alfama and Bairro Alto with its bohemian flair. The contemporary design of the 167 Deluxe Rooms and 4 Suites combines elegance and sobriety. All rooms are complemented with luxury linens and bathrobe and come equipped with hairdryer, telephone with 2 lines, airconditioning, satellite TV, Pay TV, WiFi Internet access, minibar and safe-deposit box. Our Ad Lib Restaurant, 24 hour Room Service, Business Centre and Fitness Centre, Intra-Muros Bar, Cigar Lounge and Lobby Library are waiting for you.',	image:' https://thumbs.dreamstime.com/b/grand-canal-shoppes-palazzo-venetian-hotels-luxury-shopping-62534795.jpg',	services:2,		},
 {	name:'HOTEL TABURIENTE',	phoneNumber:'453(0998)397-81-76',	address:'CALLE DOCTOR JOSE NAVEIRAS 24A',	cityCountry:'ARGENTINA',	email:'HOTEL TABURIENTEHOTEL SILKEN ATLANTIDA',	description:'is a comfortable and classically-styled hotel conveniently situated in a quiet location just off Lisbon`s Avenida da Liberdade, in the heart of the city’s main business and shopping district. Guests have at their disposal the elegant Mezzanine bar and the high-quality restaurant. Other facilities include a swimming pool with bar serving light meals.',	image:' https://thumbs.dreamstime.com/b/grand-canal-shoppes-palazzo-venetian-hotels-luxury-shopping-62534795.jpg',	services:3,		},
 {	name:'HOTEL NAUTICO',	phoneNumber:'802(7894)944-73-82',	address:'AVENIDA PROFESOR PERAZA DE AYALA 13',	cityCountry:'MEXICO',	email:'HOTEL NAUTICOHOTEL NH TENERIFE',	description:'Recently extended and renovated, the Hotel Fénix Lisboa is located in the noble Praça Marquês de Pombal, the focal point for the most important things happening in the city in terms of leisure, business, culture and shopping. Only 6 km from Lisbon International Airport, the hotel not only has the public transport network at its door, but also the city’s most important park, Parque Eduardo VII, and a few yards away, the famous Avenida da Liberdade and the no less famous Rossio, Praça dos Restauradores, Praça do Comércio and the River Tagus. Its new décor, dominated by Portuguese marble and oak, creates a timeless, welcoming Atmosphere.',	image:' https://thumbs.dreamstime.com/b/miami-beach-hotels-picture-historic-deco-ocean-drive-around-th-st-christmas-lights-visible-48713428.jpg',	services:1,		},

]